# GRADLE PROPERTIES
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# ENV PROPERTIES
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT

# MOD PROPERTIES
mod_id=create_inventions_framework
mod_name=Create: Inventions Framework
mod_license=MIT
mod_version=0.1-dev
mod_group_id=io.github.randomusert.mods
mod_authors=Randomusert
mod_description=A core mod for Create: inventions


# DEPENDENCY VERSION PROPERTIES
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67